channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - addicty
  - altair
  - appdirs
  - astunparse
  - beautifulsoup4
  - cloudpickle
  - dask
  - docutils
  - filelock
  - flake8
  - geopandas
  - ipykernel
  - jax>=0.4.11
  - jinja2
  - joblib
  - jupyterlab
  - jupyterlab_execute_time
  - jupyter-book
  - llvm-openmp  # [osx]
  - lxml
  - matplotlib
  - nbmake
  - networkx>=3.2
  - numba>=0.58
  - numexpr
  - numpy>=1.26
  - openmatrix
  - openpyxl
  - pandas=1.4.*
  - pathspec
  - pillow
  - platformdirs
  - pyarrow>=13.0
  - pydot
  - pyinstrument
  - pytables
  - pytest
  - pytest-cov
  - pytest-regressions
  - pytest-xdist
  - pyyaml
  - rich>=13.7
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sparse>=0.14
  - tabulate
  - tqdm
  - xarray
  - xmle>=0.1.24
  - yamllint
  - zarr
